FoodApp/urls.py
from . import views
from django.contrib import admin
from django.urls import path

app_name='FoodApp'

urlpatterns=[
    #/food/
    path('',views.IndexClassView.as_view(),name='index'),
    #/food/
    path('<int:pk>/',views.FoodDetail.as_view(),name='detail'),
    path('item/',views.item,name='item'),
    #/add items/
    path('add',views.CreateItem.as_view(),name='create_item'),
    #edit
    path('update/<int:id>/',views.update_item,name='update_item'),
    #delete
    path('delete/<int:id>/',views.delete_item,name='delete_item'),
]

FoodProject/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('FoodApp/',include("FoodApp.urls")),
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
]   

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

FoodApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Item(models.Model):
    def __str__(self):
        return self.item_name
    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name=models.CharField(max_length=200)
    item_desc=models.CharField(max_length=200)
    item_price=models.IntegerField()
    item_image=models.CharField(max_length=500,default="https://order.foodworks.org/assets/img/foodworks/default-menu-image-placeholder.png")

    def get_absolute_url(self):
        return reverse('FoodApp:detail',kwargs={'pk':self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    image=models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    location=models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

FoodApp/forms.py
from django import forms
from . models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_image']
        

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email=forms.EmailField()

    class Meta:
        model=User
        fields=['username','email','password1','password2']

FoodApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from FoodApp.models import Item
from FoodApp.forms import ItemForm
from django import forms
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

# Create your views here.
def index(request):
    item_list=Item.objects.all()
    context={
        'item_list':item_list,
    }
    return render(request,'FoodApp/index.html',context)


# class Based View
class IndexClassView(ListView):
    model= Item;
    template_name='FoodApp/index.html'
    context_object_name='item_list'

def item(request):
    return HttpResponse('<h1>This is an item view</h1>')

def detail(request,item_id):
    item=Item.objects.get(pk=item_id)
    context={
        'item':item,
    }
    return render(request,'FoodApp/detail.html',context)

#class Based View
class FoodDetail(DetailView):
    model=Item
    template_name='FoodApp/detail.html'

def create_item(request):
    form = ItemForm(request.POST or None)
 
    if form.is_valid():
        form.save()
        return redirect('FoodApp:index')
 
    return render(request,'FoodApp/item-form.html',{'form':form})

#class Based View
class CreateItem(CreateView):
    model = Item;
    fields = ['item_name','item_desc','item_price','item_image']
    template_name = 'FoodApp/item-form.html'

    def from_valid(self,form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)


def update_item(request,id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)
 
    if form.is_valid():
        form.save()
        return redirect('FoodApp:index')
 
    return render(request,'FoodApp/item-form.html',{'form':form,'item':item})
 
def delete_item(request,id):
    item = Item.objects.get(id=id)
 
    if request.method == 'POST':
        item.delete()
        return redirect('FoodApp:index')
 
    return render(request,'FoodApp/item-delete.html',{'item':item})

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from . forms import RegisterForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def register(request):
    if request.method=='POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username},your account is created.')
            return redirect('login')
    else:
        form= RegisterForm()
    return render(request,'users/register.html',{'form':form})

@login_required
def profilepage(request):
    return render(request,'users/profile.html')

FoodApp/templates/FoodApp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'FoodApp/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand">FoodApp</a>
        <div class="nav-brand">
            <a class="nav-item" href="{% url 'FoodApp:create_item' %}">Add Item</a>
            <a class="nav-item" href="#">Delete Item</a>
            <a class="nav-item" href="#">View Item</a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">Logout</a>
                <a href="{% url 'profile' %}">profile</a>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
       {% for message in messages %}
       <div class="alert --{{message.tag}}">
          {{message}}
       </div>
       {% endfor %}
    {% endif %}


    {% block body %}
    {% endblock %}
    
</body>
</html>

FoodApp/templates/FoodApp/detail.html
{% extends 'FoodApp/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img width="500px" src="{{item.item_image}}" class="card"/>
        </div>
        <div class="col-md-6">
            <h1>{{object.item_name}}</h1>
            <h2>{{object.item_desc}}</h2>
            <h3>${{object.item_price}}</h3>
            <a class="btn btn-danger" href="{% url 'FoodApp:delete_item' item.id %}">Delete</a>
        </div>
    </div>
</div>

{% endblock %}

FoodApp/templates/FoodApp/index.html
{% extends 'FoodApp/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body %}
    {% for item in item_list %}
        <div class="row">
            <div class="row">
                <div class="col-md-3 offset-md-2">
                    <img class="card" width="280px" height="150px" src="{{item.item_image}}"/>
                </div>
                <div class="col-md-4">
                    <h3>{{item.item_name}}</h3>
                    <h5>{{item.item_desc}}</h5>
                    <h6>${{item.item_price}}</h6>
                    <h6>user:{{item.user_name}}</h6>
                </div>
                <div class="col-md-2">
                    <a href="{% url 'FoodApp:detail' item.id %}" class="btn btn-success">Details</a>
                </div>
            </div>
        </div>

    {% endfor %}
    {% endblock %} 

</body>
</html>

    
    


















   
   

FoodApp/templates/FoodApp/item-delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete{{item.item_name}}</h2>
    <button type="submit">confirm</button>
</form>

FoodApp/templates/FoodApp/item-form.html
{% extends 'FoodApp/base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Add item
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form }}
                            <button class="btn-info" type="submit">Add</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'FoodApp/base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div card="card-title">
                       Login
                    </div>
                    <div class="card-body">
                        <form method="Post">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{field.name}}
                                    {{field}}
                                </div>
                            {% endfor %}
                            <button class="btn-info" type="submit">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}




















<!-- <form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Login</button>
</form> -->

users/templates/users/logout.html
<h1>you have been logged out</h1>

users/templates/users/profile.html
<h1>{{ user.username }}</h1>
<img src="{{ user.profile.image.url }}" width="200px" height="200px">

users/templates/users/register.html
{% extends 'FoodApp/base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        Register
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div>
                                {{ field.name }}
                                <br>
                                {{ field }}
                            </div>
                        {% endfor %}
                        <button class="btn-info" type="submit"> Signup</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}